swagger: '2.0'
info:
  version: 0.0.1
  title: Enterprise API
  description: Enterprise API
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: 'localhost:3001'
basePath: /api
tags:
  - name: Users
    description: API for users in the system
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  @@include('./paths/Users.yaml')
definitions:
  @@include('./definitions.yaml')